name: Test Older Glibc

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.io/himanshumps/ubi7_container
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install openssl
      run: yum -y install openssl openssl-devel
    - name: Build
      run: cargo build --verbose --release
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: "0.1.0"
        delete_release: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/rewrk
        tag_name: "0.1.0"
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
