name: Test Older Glibc

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.io/himanshumps/ubi7_container
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install pkg-config
      run: yum --enablerepo=* groups mark install "Development Tools"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
